export const MISSIONS = [
  {
    emoji: "❄️",
    place: "Gefrierschrank",
    code: "EIS99",
    title: "Mission 1 · Die Eiszone",
    intro:
      "Eure Schatzsuche beginnt jetzt!\n\nDer erste Hinweis wartet an einem Ort, an dem es so kalt ist, dass Wasser zu Eis wird.\n\nWo müsst ihr suchen?",
    task: "Findet den Gefrierschrank und den dort versteckten Geheimcode.",
    type: "code",
  },
  {
    emoji: "🐾",
    place: "Sofa im Wohnzimmer",
    code: "SOFA67",
    title: "Mission 2 · Tierpantomime",
    intro: "Brrrr! Ihr habt die Eiszone gefunden. 🥶",
    task: "Eine von euch stellt ein Tier dar – ohne zu sprechen und ohne Geräusche zu machen. Die anderen müssen es erraten.",
    clue: "Danach sucht den Ort, an dem man sich hinsetzt und manchmal am liebsten gar nicht mehr aufstehen möchte.",
    type: "confirm",
  },
  {
    emoji: "🧠",
    place: "Pferdebild",
    code: "PFERD3",
    title: "Mission 3 · Gedächtnistest",
    intro: "Zeit für einen Gedächtnistest!",
    task: "Merkt euch diese sieben Wörter. Ihr habt genau 15 Sekunden Zeit. Danach werden sie versteckt. Könnt ihr mindestens fünf Wörter nennen?",
    clue: "Dann sucht etwas, das galoppieren kann, aber sich hier keinen Zentimeter bewegt.",
    type: "memory",
  },
  {
    emoji: "🐴",
    place: "Fenster im Wohnzimmer",
    code: "FENSTER0",
    title: "Mission 4 · Pferdewissen",
    intro: "Sehr gut!",
    task: "Nennt gemeinsam fünf Dinge, die ein echtes Pferd gerne mag oder braucht.",
    clue: "Dann sucht dort weiter, wo ihr nach draußen schauen könnt, ohne das Haus zu verlassen.",
    type: "confirm",
  },
  {
    emoji: "🌳",
    place: "Unter einem Teller",
    code: "TELLER4",
    title: "Mission 5 · Entdeckerblick",
    intro: "Schaut kurz nach draußen.",
    task: "Findet gemeinsam: etwas Grünes, etwas, das sich bewegt, und etwas, das weiter entfernt ist als zehn Meter.",
    clue: "Danach geht dorthin, wo heute gegessen wird. Der nächste Hinweis versteckt sich unter etwas Rundem, von dem man isst.",
    type: "check",
  },
  {
    emoji: "🐹",
    place: "Beim Meerschweinchen",
    code: "HEU313",
    title: "Mission 6 · Tierrätsel",
    intro: "Jetzt ein Rätsel!",
    task: "Ich bin kein Schwein und komme nicht aus dem Meer. Ich bin klein, flauschig und mag Heu und Gemüse. Wer bin ich?",
    clue: "Die nächste Spur wartet bei mir.",
    type: "riddle",
  },
  {
    emoji: "🪞",
    place: "Spiegel im Wohnzimmer",
    code: "SPIEGEL8",
    title: "Mission 7 · Tierstimmen",
    intro: "Ihr seid schon richtig weit!",
    task: "Jede von euch macht nacheinander ein anderes Tiergeräusch. Kein Geräusch darf zweimal vorkommen!",
    clue: "Danach sucht etwas, das alles nachmacht, was ihr davor tut. Wenn ihr lacht, lacht es auch. Wenn ihr die Zunge rausstreckt, macht es genau dasselbe.",
    type: "confirm",
  },
  {
    emoji: "🎉",
    place: "Schatz",
    code: "SPIEGEL3",
    title: "Finale Mission · Die verrückteste Pose",
    intro: "Ihr seid fast am Ziel!",
    task: "Stellt euch alle vor den Spiegel. Ihr habt zehn Sekunden Zeit, gemeinsam die verrückteste Gruppenpose des ganzen Geburtstags zu machen!",
    type: "final",
  },
];

export const MEMORY_WORDS = [
  "Pizza",
  "Stern",
  "Katze",
  "Eis",
  "Krone",
  "Pferd",
  "Erdbeere",
];
